name: mnist
channels:
  - anaconda
  - defaults
  - pytorch
dependencies:
  - numpy
  - pandas
  - python=3.7.5
  - pytorch=1.4.0
  - torchvision=0.5.0
  - matplotlib
  - IPython
  - seaborn
  - pip:
      - sklearn